import { ALL_DOC_PAGES } from '@/lib/docs'
import { Callout } from '@/components/docs/Callout'

const meta = ALL_DOC_PAGES.find((p) => p.href === '/docs/conversations')!

export default function ConversationsPage() {
  return (
    <article data-docs-content>
      <div className="flex items-center justify-between mb-4 text-sm text-gray-400">
        <span>{meta.readTime}</span>
        <span>{meta.lastUpdated}</span>
      </div>

      <h1 className="text-3xl font-bold text-[#1A1035] dark:text-white mb-3">Conversations</h1>
      <p className="text-lg text-gray-500 dark:text-gray-400 mb-10 leading-relaxed">
        Review chat history, capture leads, and understand how visitors engage with your bot.
      </p>

      <h2 id="viewing-conversations" className="text-xl font-semibold text-[#1A1035] dark:text-white mt-10 mb-3 scroll-mt-20">Viewing conversations</h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
        To see every conversation your bot has had, open your bot from the Dashboard and click the <strong>Conversations</strong> tab. You&apos;ll see a list of all sessions ordered from most recent to oldest.
      </p>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
        Click any session to expand the full message thread — every visitor message, every bot response, and exact timestamps are shown.
      </p>

      <h2 id="captured-data" className="text-xl font-semibold text-[#1A1035] dark:text-white mt-10 mb-3 scroll-mt-20">What data is captured</h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">For every conversation, BotForge records:</p>
      <ul className="space-y-3 text-gray-600 dark:text-gray-400">
        {[
          { title: 'Session ID', body: 'A unique identifier for each chat session. Useful for cross-referencing with your own analytics.' },
          { title: 'Messages', body: 'The full text of every message sent by the visitor and every response generated by the bot.' },
          { title: 'Timestamps', body: 'The exact date and time of each message, displayed in your local timezone.' },
          { title: 'Lead information', body: 'If the visitor provided their name or email, this is saved alongside the conversation.' },
        ].map(({ title, body }) => (
          <li key={title} className="flex gap-3">
            <span className="text-[#6C47FF] font-bold shrink-0 mt-0.5">→</span>
            <span><strong className="text-[#1A1035] dark:text-white">{title}</strong> — {body}</span>
          </li>
        ))}
      </ul>

      <h2 id="lead-capture" className="text-xl font-semibold text-[#1A1035] dark:text-white mt-10 mb-3 scroll-mt-20">Lead capture</h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
        BotForge saves the visitor&apos;s name and email address when they share it during a conversation. Leads are visible in the <strong>Leads</strong> tab — each entry shows the visitor&apos;s name, email, chat date, and a link to the full conversation.
      </p>
      <Callout variant="tip" title="Encourage lead capture">
        Add a line to your system prompt such as: &ldquo;If the visitor asks about pricing or places an order, politely ask for their name and email so we can follow up.&rdquo;
      </Callout>

      <h2 id="analytics" className="text-xl font-semibold text-[#1A1035] dark:text-white mt-10 mb-3 scroll-mt-20">Analytics overview</h2>
      <p className="text-gray-600 dark:text-gray-400 leading-relaxed mb-4">
        The <strong>Analytics</strong> tab gives a high-level view of how your bot is performing:
      </p>
      <ul className="space-y-3 text-gray-600 dark:text-gray-400 mb-6">
        {[
          { title: 'Total messages', body: 'Cumulative messages received — useful for tracking growth and monitoring usage against your plan limit.' },
          { title: 'Daily chart', body: 'Message volume per day over the last 30 days, so you can spot traffic patterns and peak times.' },
          { title: 'Top questions', body: 'The most frequently asked questions, ranked by volume. Use this to prioritise knowledge base additions.' },
          { title: 'Unanswered rate', body: 'Percentage of messages where the bot triggered its fallback because it couldn\'t find a confident answer.' },
        ].map(({ title, body }) => (
          <li key={title} className="flex gap-3">
            <span className="text-[#6C47FF] font-bold shrink-0 mt-0.5">→</span>
            <span><strong className="text-[#1A1035] dark:text-white">{title}</strong> — {body}</span>
          </li>
        ))}
      </ul>
      <Callout variant="warning" title="High unanswered rate?">
        Aim to keep it below 15%. If it&apos;s higher, check top unanswered questions and add matching FAQs to your{' '}
        <a href="/docs/knowledge-base" className="text-[#6C47FF] hover:underline">knowledge base</a>.
      </Callout>
    </article>
  )
}
